model:
  name: PINN
  architecture:
    - layer:
        type: Linear
        in_features: 5 #t + States + Control inputs
        out_features: 32
    - layer:
        type: SiLU
        inplace: False
    - layer:
        type: Linear
        in_features: 32
        out_features: 32
    - layer:
        type: SiLU
        inplace: False        
    - layer:
        type: Linear
        in_features: 32
        out_features: 32
    - layer:
        type: SiLU
        inplace: False
    - layer:
        type: Linear
        in_features: 32
        out_features: 3 # States
        bias: False
